### ISSUE TITLE
BUG - Table Repo Team does not exist

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_github#21]
**Are you a current Fivetran customer?** 

Fivetran example Issue

**Describe the bug**

When I install the dbt package and try to run I am presented with an error stating that the `repo_team` table does not exist and then I see failures throughout my dbt run. 

I do not have the `repo_team` table being synced in my warehouse currently. How can I run the package without referencing this source table?

**Steps to reproduce**
1. Do not have the `repo_team` table synced in your warehouse
2. Install the fivetran_github dbt package
3. Run the dbt package
4. See the failure

**Expected behavior**

The package can run without needing to reference the `repo_team` source table.

**Project variables configuration**

```yml
name: 'development'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: my_profile

vars:
  github_schema: github_test
  github_database: test_db
```

**Package Version**

```yml
packages:
  - package: fivetran/github
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
