### ISSUE TITLE
BUG - Pull Requests are Not Included in the Github__Issues Model

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_github#22]
**Are you a current Fivetran customer?** 

Fivetran example Issue

**Describe the bug**

When viewing the final models from this package I have noticed the Pull Requests are not included in the `github__issues` final model. I know Github interprets Pull Requests as Issues and I wonder why they are being filtered out? 

Is there a way I may view the Pull Requests in a similar fashion? If so, how may I union these two tables together so they are in one place?

**Steps to reproduce**
1. Run the `fivetran_github` dbt package
2. View the `github__issues` final model
3. See that there are no PRs included

**Expected behavior**

PRs are included in the final output model of `github__issues` or there is a way to add PRs to the issues table.

**Project variables configuration**

```yml
name: 'development'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: my_profile

vars:
  github_schema: github_test
  github_database: test_db
```

**Package Version**

```yml
packages:
  - package: fivetran/github
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
