### ISSUE TITLE
BUG - Issue ID unique test fails on github__pull_requests

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_github#23]
**Are you a current Fivetran customer?** 

Fivetran example Issue

**Describe the bug**

When I run `dbt test` on the `fivetran/github` package I find that the dbt test for uniqueness of `issue_id` on `github__pull_requests` fails. It looks like these are not in fact unique. 

**Steps to reproduce**
1. Install the `fivetran/github` dbt package
2. run `dbt test`
3. See the uniqueness test fail for `github__pull_requests`

**Expected behavior**

The test for uniqueness of issue_id in `github__pull_requests` does not fail.

**Project variables configuration**

```yml
name: 'development'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: my_profile

vars:
  github_schema: github_test
  github_database: test_db
```

**Package Version**

```yml
packages:
  - package: fivetran/github
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
