### ISSUE TITLE
BUG - Error building github__issues model on Redshift due to problem with date_diff function 

### ISSUE THREAD

**Issue by kpounder** [fivetran/dbt_github#25]
**Are you a current Fivetran customer?** 
Kyle Pounder, Director of Analytics, Wealth 

**Describe the bug**
Running `dbt run` returns an error on Redshift when building the `github__issues` model. The error message that I get is 

```
Database Error in model github__issues (models/github__issues.sql)
  function pg_catalog.date_diff("unknown", timestamp with time zone, timestamp with time zone) does not exist
  HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
  compiled SQL at target/run/github/models/github__issues.sql
```

**Steps to reproduce**
1. Import the `fivetran/github` package like this:

```
  - package: fivetran/github
    version: [">=0.4.0", "<0.5.0"]
```

2. Run `dbt run`

**Expected behavior**
The models should build with no error. 

**Project variables configuration**
```yml
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'wealth'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Vars
vars:
  github_source:
    github_database: product
    github_schema: src_fivetran_github
```

**Package Version**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0
  - package: fivetran/github
    version: [">=0.4.0", "<0.5.0"]
    
```

**Warehouse**

 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
With some quick research, I found the same issue [https://github.com/fivetran/dbt_jira_source/issues/23] with the dbt Jira package. Not sure if that one was solved -- and same solution could be applied here. 

**Screenshots**
N/A

**Please indicate the level of urgency** 
I'm using Github to run a POC with Fivetran. My trial expires soon. 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
