### ISSUE TITLE
BUG - Github DBT tables do not populate with data

### ISSUE THREAD

**Issue by merocole** [fivetran/dbt_github#29]
**Are you a current Fivetran customer?** 
Yes, Co-Founder, Mero Technologies

**Describe the bug**
I am successfully using DBT packages for many other source transformations successfully (Hubspot for example). However, for the github packages, none of the github_* tables populate with data despite them being created. The tables generated from github_source work fine so it is just the github package where the problem is (and all tables with stg_github* are populated with data).

Furthermore, no issues are shown in the DBT logs after running and all data available from the github API is in redshift. 

**Steps to reproduce**
1. run dbt after adding the github packages (v 5.0.0) connected to redshift
2. go to any table with the prefix github_

**Expected behavior**
Data should be populated in the tables with the prefix github_*

**Project variables configuration**

```yml


name: 'dbt_datapipeling'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_datapipeling'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_datapipeling:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view




```

**Package Version**

```yml
packages:
  - package: fivetran/hubspot
    version: 0.5.1
  - package: fivetran/jira
    version: 0.7.0
  - package: fivetran/github
    version: 0.5.0
```

**Warehouse**

 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
I noticed that the staging tables and the tables made from the "github" package are in the same schema. Is this expected? 

**Screenshots**

**Please indicate the level of urgency** 
Just testing

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
